
export interface Country {
    name: string
    code: string
    dial_code: string
    flag: string
}

export const COUNTRIES: Country[] = [
    { name: "Afganistán", code: "AF", dial_code: "+93", flag: "🇦�" },
    { name: "Albania", code: "AL", dial_code: "+355", flag: "��" },
    { name: "Alemania", code: "DE", dial_code: "+49", flag: "��" },
    { name: "Andorra", code: "AD", dial_code: "+376", flag: "��" },
    { name: "Angola", code: "AO", dial_code: "+244", flag: "�🇴" },
    { name: "Antigua y Barbuda", code: "AG", dial_code: "+1", flag: "��" },
    { name: "Arabia Saudita", code: "SA", dial_code: "+966", flag: "🇦" },
    { name: "Argelia", code: "DZ", dial_code: "+213", flag: "��" },
    { name: "Argentina", code: "AR", dial_code: "+54", flag: "��" },
    { name: "Armenia", code: "AM", dial_code: "+374", flag: "��" },
    { name: "Australia", code: "AU", dial_code: "+61", flag: "��" },
    { name: "Austria", code: "AT", dial_code: "+43", flag: "��" },
    { name: "Azerbaiyán", code: "AZ", dial_code: "+994", flag: "🇦�" },
    { name: "Bahamas", code: "BS", dial_code: "+1", flag: "��" },
    { name: "Bangladés", code: "BD", dial_code: "+880", flag: "��" },
    { name: "Barbados", code: "BB", dial_code: "+1", flag: "��" },
    { name: "Baréin", code: "BH", dial_code: "+973", flag: "��" },
    { name: "Bélgica", code: "BE", dial_code: "+32", flag: "��" },
    { name: "Belice", code: "BZ", dial_code: "+501", flag: "��" },
    { name: "Benín", code: "BJ", dial_code: "+229", flag: "��" },
    { name: "Bielorrusia", code: "BY", dial_code: "+375", flag: "🇾" },
    { name: "Birmania", code: "MM", dial_code: "+95", flag: "��" },
    { name: "Bolivia", code: "BO", dial_code: "+591", flag: "�🇴" },
    { name: "Bosnia y Herzegovina", code: "BA", dial_code: "+387", flag: "🇧�" },
    { name: "Botsuana", code: "BW", dial_code: "+267", flag: "🇧🇼" },
    { name: "Brasil", code: "BR", dial_code: "+55", flag: "🇧�" },
    { name: "Brunéi", code: "BN", dial_code: "+673", flag: "🇧�" },
    { name: "Bulgaria", code: "BG", dial_code: "+359", flag: "��" },
    { name: "Burkina Faso", code: "BF", dial_code: "+226", flag: "��" },
    { name: "Burundi", code: "BI", dial_code: "+257", flag: "��" },
    { name: "Bután", code: "BT", dial_code: "+975", flag: "��" },
    { name: "Cabo Verde", code: "CV", dial_code: "+238", flag: "��" },
    { name: "Camboya", code: "KH", dial_code: "+855", flag: "��" },
    { name: "Camerún", code: "CM", dial_code: "+237", flag: "🇨�" },
    { name: "Canadá", code: "CA", dial_code: "+1", flag: "��" },
    { name: "Catar", code: "QA", dial_code: "+974", flag: "��" },
    { name: "Chad", code: "TD", dial_code: "+235", flag: "��" },
    { name: "Chile", code: "CL", dial_code: "+56", flag: "��" },
    { name: "China", code: "CN", dial_code: "+86", flag: "��" },
    { name: "Chipre", code: "CY", dial_code: "+357", flag: "��" },
    { name: "Colombia", code: "CO", dial_code: "+57", flag: "��" },
    { name: "Comoras", code: "KM", dial_code: "+269", flag: "�🇲" },
    { name: "Corea del Norte", code: "KP", dial_code: "+850", flag: "��" },
    { name: "Corea del Sur", code: "KR", dial_code: "+82", flag: "��" },
    { name: "Costa de Marfil", code: "CI", dial_code: "+225", flag: "🇨🇮" },
    { name: "Costa Rica", code: "CR", dial_code: "+506", flag: "��" },
    { name: "Croacia", code: "HR", dial_code: "+385", flag: "�🇷" },
    { name: "Cuba", code: "CU", dial_code: "+53", flag: "��" },
    { name: "Dinamarca", code: "DK", dial_code: "+45", flag: "��" },
    { name: "Dominica", code: "DM", dial_code: "+1", flag: "🇩🇲" },
    { name: "Ecuador", code: "EC", dial_code: "+593", flag: "��" },
    { name: "Egipto", code: "EG", dial_code: "+20", flag: "��" },
    { name: "El Salvador", code: "SV", dial_code: "+503", flag: "��" },
    { name: "Emiratos Árabes Unidos", code: "AE", dial_code: "+971", flag: "🇦🇪" },
    { name: "Eritrea", code: "ER", dial_code: "+291", flag: "��" },
    { name: "Eslovaquia", code: "SK", dial_code: "+421", flag: "��" },
    { name: "Eslovenia", code: "SI", dial_code: "+386", flag: "��" },
    { name: "España", code: "ES", dial_code: "+34", flag: "��" },
    { name: "Estados Unidos", code: "US", dial_code: "+1", flag: "��" },
    { name: "Estonia", code: "EE", dial_code: "+372", flag: "��" },
    { name: "Esuatini", code: "SZ", dial_code: "+268", flag: "🇸�" },
    { name: "Etiopía", code: "ET", dial_code: "+251", flag: "��" },
    { name: "Filipinas", code: "PH", dial_code: "+63", flag: "��" },
    { name: "Finlandia", code: "FI", dial_code: "+358", flag: "��" },
    { name: "Fiyi", code: "FJ", dial_code: "+679", flag: "��" },
    { name: "Francia", code: "FR", dial_code: "+33", flag: "��" },
    { name: "Gabón", code: "GA", dial_code: "+241", flag: "��" },
    { name: "Gambia", code: "GM", dial_code: "+220", flag: "��" },
    { name: "Georgia", code: "GE", dial_code: "+995", flag: "🇬🇪" },
    { name: "Ghana", code: "GH", dial_code: "+233", flag: "��" },
    { name: "Granada", code: "GD", dial_code: "+1", flag: "🇬🇩" },
    { name: "Grecia", code: "GR", dial_code: "+30", flag: "��" },
    { name: "Guatemala", code: "GT", dial_code: "+502", flag: "��" },
    { name: "Guinea", code: "GN", dial_code: "+224", flag: "��" },
    { name: "Guinea Ecuatorial", code: "GQ", dial_code: "+240", flag: "��" },
    { name: "Guinea-Bisáu", code: "GW", dial_code: "+245", flag: "��" },
    { name: "Guyana", code: "GY", dial_code: "+592", flag: "�🇾" },
    { name: "Haití", code: "HT", dial_code: "+509", flag: "��" },
    { name: "Honduras", code: "HN", dial_code: "+504", flag: "��" },
    { name: "Hungría", code: "HU", dial_code: "+36", flag: "��" },
    { name: "India", code: "IN", dial_code: "+91", flag: "��" },
    { name: "Indonesia", code: "ID", dial_code: "+62", flag: "��" },
    { name: "Irak", code: "IQ", dial_code: "+964", flag: "��" },
    { name: "Irán", code: "IR", dial_code: "+98", flag: "��" },
    { name: "Irlanda", code: "IE", dial_code: "+353", flag: "�🇪" },
    { name: "Islandia", code: "IS", dial_code: "+354", flag: "🇮🇸" },
    { name: "Israel", code: "IL", dial_code: "+972", flag: "��" },
    { name: "Italia", code: "IT", dial_code: "+39", flag: "��" },
    { name: "Jamaica", code: "JM", dial_code: "+1", flag: "��" },
    { name: "Japón", code: "JP", dial_code: "+81", flag: "��" },
    { name: "Jordania", code: "JO", dial_code: "+962", flag: "��" },
    { name: "Kazajistán", code: "KZ", dial_code: "+7", flag: "��" },
    { name: "Kenia", code: "KE", dial_code: "+254", flag: "��" },
    { name: "Kirguistán", code: "KG", dial_code: "+996", flag: "��" },
    { name: "Kiribati", code: "KI", dial_code: "+686", flag: "��" },
    { name: "Kosovo", code: "XK", dial_code: "+383", flag: "��" },
    { name: "Kuwait", code: "KW", dial_code: "+965", flag: "��" },
    { name: "Laos", code: "LA", dial_code: "+856", flag: "��" },
    { name: "Lesoto", code: "LS", dial_code: "+266", flag: "��" },
    { name: "Letonia", code: "LV", dial_code: "+371", flag: "🇱🇻" },
    { name: "Líbano", code: "LB", dial_code: "+961", flag: "��" },
    { name: "Liberia", code: "LR", dial_code: "+231", flag: "��" },
    { name: "Libia", code: "LY", dial_code: "+218", flag: "🇾" },
    { name: "Liechtenstein", code: "LI", dial_code: "+423", flag: "��" },
    { name: "Lituania", code: "LT", dial_code: "+370", flag: "��" },
    { name: "Luxemburgo", code: "LU", dial_code: "+352", flag: "�🇺" },
    { name: "Macedonia del Norte", code: "MK", dial_code: "+389", flag: "🇰" },
    { name: "Madagascar", code: "MG", dial_code: "+261", flag: "��" },
    { name: "Malasia", code: "MY", dial_code: "+60", flag: "��" },
    { name: "Malaui", code: "MW", dial_code: "+265", flag: "��" },
    { name: "Maldivas", code: "MV", dial_code: "+960", flag: "��" },
    { name: "Malí", code: "ML", dial_code: "+223", flag: "��" },
    { name: "Malta", code: "MT", dial_code: "+356", flag: "��" },
    { name: "Marruecos", code: "MA", dial_code: "+212", flag: "�🇦" },
    { name: "Mauricio", code: "MU", dial_code: "+230", flag: "��" },
    { name: "Mauritania", code: "MR", dial_code: "+222", flag: "🇷" },
    { name: "México", code: "MX", dial_code: "+52", flag: "��" },
    { name: "Micronesia", code: "FM", dial_code: "+691", flag: "��" },
    { name: "Moldavia", code: "MD", dial_code: "+373", flag: "�🇩" },
    { name: "Mónaco", code: "MC", dial_code: "+377", flag: "��" },
    { name: "Mongolia", code: "MN", dial_code: "+976", flag: "�🇳" },
    { name: "Montenegro", code: "ME", dial_code: "+382", flag: "��" },
    { name: "Mozambique", code: "MZ", dial_code: "+258", flag: "��" },
    { name: "Namibia", code: "NA", dial_code: "+264", flag: "��" },
    { name: "Nauru", code: "NR", dial_code: "+674", flag: "��" },
    { name: "Nepal", code: "NP", dial_code: "+977", flag: "��" },
    { name: "Nicaragua", code: "NI", dial_code: "+505", flag: "��" },
    { name: "Níger", code: "NE", dial_code: "+227", flag: "��" },
    { name: "Nigeria", code: "NG", dial_code: "+234", flag: "��" },
    { name: "Noruega", code: "NO", dial_code: "+47", flag: "��" },
    { name: "Nueva Zelanda", code: "NZ", dial_code: "+64", flag: "��" },
    { name: "Omán", code: "OM", dial_code: "+968", flag: "��" },
    { name: "Países Bajos", code: "NL", dial_code: "+31", flag: "��" },
    { name: "Pakistán", code: "PK", dial_code: "+92", flag: "��" },
    { name: "Palaos", code: "PW", dial_code: "+680", flag: "��" },
    { name: "Palestina", code: "PS", dial_code: "+970", flag: "��" },
    { name: "Panamá", code: "PA", dial_code: "+507", flag: "��" },
    { name: "Papúa Nueva Guinea", code: "PG", dial_code: "+675", flag: "��" },
    { name: "Paraguay", code: "PY", dial_code: "+595", flag: "🇾" },
    { name: "Perú", code: "PE", dial_code: "+51", flag: "🇪" },
    { name: "Polonia", code: "PL", dial_code: "+48", flag: "��" },
    { name: "Portugal", code: "PT", dial_code: "+351", flag: "🇵�" },
    { name: "Reino Unido", code: "GB", dial_code: "+44", flag: "��" },
    { name: "República Centroafricana", code: "CF", dial_code: "+236", flag: "��" },
    { name: "República Checa", code: "CZ", dial_code: "+420", flag: "��" },
    { name: "República del Congo", code: "CG", dial_code: "+242", flag: "�🇬" },
    { name: "República Democrática del Congo", code: "CD", dial_code: "+243", flag: "��" },
    { name: "República Dominicana", code: "DO", dial_code: "+1", flag: "��" },
    { name: "Ruanda", code: "RW", dial_code: "+250", flag: "��" },
    { name: "Rumanía", code: "RO", dial_code: "+40", flag: "��" },
    { name: "Rusia", code: "RU", dial_code: "+7", flag: "��" },
    { name: "Samoa", code: "WS", dial_code: "+685", flag: "��" },
    { name: "San Cristóbal y Nieves", code: "KN", dial_code: "+1", flag: "��" },
    { name: "San Marino", code: "SM", dial_code: "+378", flag: "��" },
    { name: "San Vicente y las Granadinas", code: "VC", dial_code: "+1", flag: "��" },
    { name: "Santa Lucía", code: "LC", dial_code: "+1", flag: "��" },
    { name: "Santo Tomé y Príncipe", code: "ST", dial_code: "+239", flag: "��" },
    { name: "Senegal", code: "SN", dial_code: "+221", flag: "�🇳" },
    { name: "Serbia", code: "RS", dial_code: "+381", flag: "��" },
    { name: "Seychelles", code: "SC", dial_code: "+248", flag: "��" },
    { name: "Sierra Leona", code: "SL", dial_code: "+232", flag: "��" },
    { name: "Singapur", code: "SG", dial_code: "+65", flag: "��" },
    { name: "Siria", code: "SY", dial_code: "+963", flag: "��" },
    { name: "Somalia", code: "SO", dial_code: "+252", flag: "��" },
    { name: "Sri Lanka", code: "LK", dial_code: "+94", flag: "��" },
    { name: "Sudáfrica", code: "ZA", dial_code: "+27", flag: "��" },
    { name: "Sudán", code: "SD", dial_code: "+249", flag: "��" },
    { name: "Sudán del Sur", code: "SS", dial_code: "+211", flag: "�🇸" },
    { name: "Suecia", code: "SE", dial_code: "+46", flag: "🇸�" },
    { name: "Suiza", code: "CH", dial_code: "+41", flag: "��" },
    { name: "Surinam", code: "SR", dial_code: "+597", flag: "��" },
    { name: "Tailandia", code: "TH", dial_code: "+66", flag: "��" },
    { name: "Taiwán", code: "TW", dial_code: "+886", flag: "��" },
    { name: "Tanzania", code: "TZ", dial_code: "+255", flag: "��" },
    { name: "Tayikistán", code: "TJ", dial_code: "+992", flag: "��" },
    { name: "Timor Oriental", code: "TL", dial_code: "+670", flag: "��" },
    { name: "Togo", code: "TG", dial_code: "+228", flag: "��" },
    { name: "Tonga", code: "TO", dial_code: "+676", flag: "��" },
    { name: "Trinidad y Tobago", code: "TT", dial_code: "+1", flag: "��" },
    { name: "Túnez", code: "TN", dial_code: "+216", flag: "��" },
    { name: "Turkmenistán", code: "TM", dial_code: "+993", flag: "��" },
    { name: "Turquía", code: "TR", dial_code: "+90", flag: "��" },
    { name: "Tuvalu", code: "TV", dial_code: "+688", flag: "🇹🇻" },
    { name: "Ucrania", code: "UA", dial_code: "+380", flag: "��" },
    { name: "Uganda", code: "UG", dial_code: "+256", flag: "��" },
    { name: "Uruguay", code: "UY", dial_code: "+598", flag: "��" },
    { name: "Uzbekistán", code: "UZ", dial_code: "+998", flag: "��" },
    { name: "Vanuatu", code: "VU", dial_code: "+678", flag: "��" },
    { name: "Vaticano", code: "VA", dial_code: "+39", flag: "�🇦" },
    { name: "Venezuela", code: "VE", dial_code: "+58", flag: "��" },
    { name: "Vietnam", code: "VN", dial_code: "+84", flag: "�🇳" },
    { name: "Yemen", code: "YE", dial_code: "+967", flag: "��" },
    { name: "Yibuti", code: "DJ", dial_code: "+253", flag: "��" },
    { name: "Zambia", code: "ZM", dial_code: "+260", flag: "��" },
    { name: "Zimbabue", code: "ZW", dial_code: "+263", flag: "��" }
]
